import {
  MdDashboard,
  MdFolder,
  MdAccountTree,
  MdBarChart,
  MdNotifications,
  MdPeople,
  MdSettings,
  MdEvent,
  MdHistory,
  MdWarning,
  MdWork,
  MdSchool,
  MdApartment,
  MdPrint,
} from "react-icons/md";

export const sidebarMenus = {
  ROLE_ADMIN: {
    title: "Assistant Registrar",
    shortTitle: "AR",
    items: [
      { label: "Dashboard", icon: MdDashboard, path: "/dashboard" },
      { label: "Packets", icon: MdFolder, path: "/packets" },
      { label: "Workflow", icon: MdAccountTree, path: "/workflow" },
      { label: "Printing Schedule", icon: MdPrint, path: "/printing/schedule" },
      { label: "Courses", icon: MdSchool, path: "/courses" },
      { label: "Departments", icon: MdApartment, path: "/departments" },
      { label: "Reports", icon: MdBarChart, path: "/reports" },
      { label: "Notifications", icon: MdNotifications, path: "/notifications" },
      { label: "User Management", icon: MdPeople, path: "/users" },
      { label: "Settings", icon: MdSettings, path: "/settings" },
    ],
  },
  ROLE_MODERATOR: {
    title: "Moderator",
    shortTitle: "MOD",
    items: [
      { label: "Dashboard", icon: MdDashboard, path: "/dashboard" },
      { label: "Packets", icon: MdFolder, path: "/packets" },
      { label: "Workflow", icon: MdAccountTree, path: "/workflow" },
      { label: "Notifications", icon: MdNotifications, path: "/notifications" },
      { label: "Settings", icon: MdSettings, path: "/settings" },
    ],
  },
  ROLE_USER: {
    title: "Lecturer",
    shortTitle: "LEC",
    items: [
      { label: "Dashboard", icon: MdDashboard, path: "/dashboard" },
      { label: "My Exam Packets", icon: MdFolder, path: "/packets" },
      { label: "Workflow Overview", icon: MdAccountTree, path: "/workflow" },
      { label: "Schedule & Deadlines", icon: MdEvent, path: "/lecturer/calendar" },
      { label: "Printing Schedule", icon: MdPrint, path: "/printing/schedule" },
      { label: "Previous Records", icon: MdHistory, path: "/lecturer/previous" },
      { label: "Notifications", icon: MdNotifications, path: "/notifications" },
      { label: "Settings", icon: MdSettings, path: "/settings" },
    ],
  },
  ROLE_GUEST: {
    title: "Head of Department",
    shortTitle: "HOD",
    items: [
      { label: "Overview", icon: MdDashboard, path: "/dashboard" },
      { label: "Department Packets", icon: MdFolder, path: "/hod/packets" },
      { label: "Department Courses", icon: MdSchool, path: "/hod/courses" },
      { label: "My Department", icon: MdApartment, path: "/hod/department" },
      { label: "Staff Workload", icon: MdWork, path: "/hod/workload" },
      { label: "Department Reports", icon: MdBarChart, path: "/hod/reports" },
      { label: "Overdue Items", icon: MdWarning, path: "/hod/overdue" },
      { label: "Academic Archives", icon: MdHistory, path: "/hod/previous" },
      { label: "Notifications", icon: MdNotifications, path: "/notifications" },
      { label: "Settings", icon: MdSettings, path: "/settings" },
    ],
  },
  ROLE_SYSTEM_ADMIN: {
    title: "System Administrator",
    shortTitle: "SYS",
    items: [
      { label: "Dashboard", icon: MdDashboard, path: "/dashboard" },
      { label: "User Management", icon: MdPeople, path: "/users" },
      { label: "Departments", icon: MdApartment, path: "/departments" },
      { label: "Courses", icon: MdSchool, path: "/courses" },
      { label: "Packets", icon: MdFolder, path: "/packets" },
      { label: "Printing Schedule", icon: MdPrint, path: "/printing/schedule" },
      { label: "Workflow", icon: MdAccountTree, path: "/workflow" },
      { label: "Reports", icon: MdBarChart, path: "/reports" },
      { label: "Notifications", icon: MdNotifications, path: "/notifications" },
      { label: "Settings", icon: MdSettings, path: "/settings" },
    ],
  },
};
